env:
  PLUGIN_DAEMON_OFF: true
  DOCKER_HOST: tcp://build-agent.default:2375
stages:
- name: Build
  steps:
  - runScriptConfig:
      image: 127.0.0.1:34688/dotnet/core/sdk_npm:3.1
      shellScript: |-
        export PATH="$PATH:/root/.dotnet/tools"
        dotnet tool install --global Cake.Tool --version 0.38.4
        dotnet cake build.cake --target=Sample
        ls -al ./artifacts
- name: Dockerize1
  steps:
  - publishImageConfig:
      dockerfilePath: ./artifacts/Hypomos.Web/Dockerfile
      buildContext: ./artifacts/Hypomos.Web
      tag: hypomos/web:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34688
- name: Dockerize2
  steps:
  - publishImageConfig:
      dockerfilePath: ./artifacts/Hypomos.Silo/Dockerfile
      buildContext: ./artifacts/Hypomos.Silo
      tag: hypomos/silo:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34688
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
