apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterversions.orleans.dot.net
spec:
  group: orleans.dot.net
  version: v1
  scope: Namespaced
  names:
    plural: clusterversions
    singular: clusterversion
    kind: OrleansClusterVersion
    shortNames:
    - ocv
---
    apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    metadata:
      name: silos.orleans.dot.net
    spec:
      group: orleans.dot.net
      version: v1
      scope: Namespaced
      names:
        plural: silos
        singular: silo
        kind: OrleansSilo
        shortNames:
        - oso
---
# creating roles for ressources
apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRole
metadata:
  name: orleans-manager
rules:
- apiGroups: ["orleans.dot.net"] 
  resources: ["clusterversions", "silos"] 
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"] 
---
# granting access for: system:serviceaccount:hypomos-dev:default
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-orleans
  namespace: hypomos-dev
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: ClusterRole
  name: orleans-manager
  apiGroup: rbac.authorization.k8s.io